In [1]:
import pandas as pd

import matplotlib.pyplot as plt

import warnings; warnings.filterwarnings("ignore")

from Helper import *

In [2]:
import numpy as np

film_df = pd.read_csv("/tmp/movies.csv")

film_df = filmer(film_df)

film_df.iloc[:5]

MovieID                        Title  \
0        1                    Toy Story   
1        2                      Jumanji   
2        3             Grumpier Old Men   
3        4            Waiting to Exhale   
4        5  Father of the Bride Part II   

                                         Genre Tahun  
0  Adventure Animation Children Comedy Fantasy  1995  
1                   Adventure Children Fantasy  1995  
2                               Comedy Romance  1995  
3                         Comedy Drama Romance  1995  
4                                       Comedy  1995

In [3]:
film_df.isnull().sum().sum()

0

In [4]:
film_df.shape

(9708, 4)

In [5]:
result_genre = counter(film_df["Genre"])

len(result_genre)

19

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.metrics.pairwise import linear_kernel

In [7]:
tif = TfidfVectorizer(stop_words="english")

tfidf = tif.fit_transform(film_df["Genre"])

tfidf.shape

(9708, 19)

In [8]:
film_similarity = linear_kernel(tfidf, tfidf)

film_similarity.shape

(9708, 9708)

In [9]:
len(film_similarity[0])

9708

In [10]:
film_similarity[0][:10]

array([1.        , 0.8136036 , 0.15259961, 0.13500041, 0.26738778,
       0.        , 0.15259961, 0.65470981, 0.        , 0.26241348])

In [11]:
film_similarity[5][:10]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       1.        , 0.        , 0.        , 0.54929139, 0.59953789])

In [12]:
film_similarity[8][:10]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.54929139, 0.        , 0.        , 1.        , 0.55303337])

In [13]:
def ind_titler(i):
    return film_df.iloc[i, 1]

def title_ind(t):
    return film_df[film_df["Title"] == t].index[0]

In [14]:
t = title_ind("Toy Story")

ml_list = list(enumerate(film_similarity[int(t)]))

ml_list = sorted(ml_list, key = lambda x:x[1], reverse=True)

len(ml_list)

9708

In [15]:
def recommender(title, threshold):

  m_list = list(enumerate(film_similarity[int(title_ind(title))]))

  m_list = sorted(m_list, key = lambda i : i[1], reverse=True)

  m_list = m_list[:threshold]

  m_list = list(filter(lambda i : i[0] != title_ind(title), m_list))

  m_list = [ind_titler(m_list[i][0]) for i in range(len(m_list))]

  return film_df[film_df["Title"].isin(m_list)]

recommender("Jumanji", 10)

MovieID                                              Title  \
53         60                        Indian in the Cupboard, The   
109       126                         NeverEnding Story III, The   
767      1009                           Escape to Witch Mountain   
1514     2043                 Darby O'Gill and the Little People   
1556     2093                                       Return to Oz   
1617     2161                             NeverEnding Story, The   
1618     2162        NeverEnding Story II: The Next Chapter, The   
1799     2399                             Santa Claus: The Movie   
3574     4896  Harry Potter and the Sorcerer's Stone (a.k.a. ...   

                           Genre Tahun  
53    Adventure Children Fantasy  1995  
109   Adventure Children Fantasy  1994  
767   Adventure Children Fantasy  1975  
1514  Adventure Children Fantasy  1959  
1556  Adventure Children Fantasy  1985  
1617  Adventure Children Fantasy  1984  
1618  Adventure Children Fantasy  1990  
1799  Adventure Children Fantasy  1985  
3574  Adventure Children Fantasy  2001

In [16]:
film_df[film_df["Title"]=="Jumanji"]

MovieID    Title                       Genre Tahun
1        2  Jumanji  Adventure Children Fantasy  1995